#!/bin/bash

###
# ranmac is a simple bash based mac address randomizer
###

# Colorizing Output
RED='\033[0;31m'
NC='\033[0m'

# Elevating check
if [[ $EUID > 0 ]]
then echo -e "Run ranmac with sudo${RED}\nElevation is required for handling network interfaces.${NC}"
exit 1
fi

device_inf=$1

if [[ -z $device_inf ]]
then
    echo -e "No network interface provided\nUsage - ./ranmac <interface>"
    echo -e "eg    - ./ranmac eth0"
else
    # Generating a randomized mac address
    random_mac=$(hexdump -n 6 -ve '1/1 "%.2x "' /dev/random | awk -v a="2,6,a,e" -v r="$RANDOM" 'BEGIN{srand(r);}NR==1{split(a,b,",");r=int(rand()*4+1);printf "%s%s:%s:%s:%s:%s:%s\n",substr($1,0,1),b[r],$2,$3,$4,$5,$6}')
    # Saving current mac address in a curr_mac.bak file in case you need to set it back
    ip -br link show eth0 | awk '{ print $2 }' > curr_mac.bak
    # Setting the new randomized mac address on the selected interface
    sudo ip link set dev $device_inf down
    sudo ip link set dev $device_inf address $random_mac
    sudo ip link set dev $device_inf up    
fi
